apiVersion: v1
kind: Pod
metadata:
  name: winticket
spec:
  containers:
  - image: winticket:0.0.8
    name: winticket
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: winticket-storage
      mountPath: "/var/app/current/stage/opt/docker"
    ports:
    - containerPort: 9000
      name: http
  volumes:
  - name: winticket-storage
    persistentVolumeClaim:
     claimName: winticket-pv-claim